// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileUpload.proto

package com.example.samplegrpcapp;

public final class FileUpload {
  private FileUpload() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020FileUpload.proto\022\031com.example.samplegr" +
      "pcapp\032\rRequest.proto\032\016Response.proto2\301\001\n" +
      "\rUploadService\022U\n\006upload\022\".com.example.s" +
      "amplegrpcapp.Request\032#.com.example.sampl" +
      "egrpcapp.Response\"\000(\001\022Y\n\014upload_chunk\022\"." +
      "com.example.samplegrpcapp.Request\032#.com." +
      "example.samplegrpcapp.Response\"\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          RequestOuterClass.getDescriptor(),
          ResponseOuterClass.getDescriptor(),
        });
    RequestOuterClass.getDescriptor();
    ResponseOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
