// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileUpload.proto

package com.example.samplegrpcapp;

public final class ProtoUploadService {
  private ProtoUploadService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020FileUpload.proto\022\nUploadFile\032\rRequest." +
      "proto\032\016Response.proto2\205\001\n\rUploadService\022" +
      "7\n\006upload\022\023.UploadFile.Request\032\024.UploadF" +
      "ile.Response\"\000(\001\022;\n\014upload_chunk\022\023.Uploa" +
      "dFile.Request\032\024.UploadFile.Response\"\000B/\n" +
      "\031com.example.samplegrpcappB\022ProtoUploadS" +
      "erviceb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ProtoRequest.getDescriptor(),
          ProtoResponse.getDescriptor(),
        });
    ProtoRequest.getDescriptor();
    ProtoResponse.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
