// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

package com.example.samplegrpcapp;

public final class ProtoRequest {
  private ProtoRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:samplegrpcapp.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.samplegrpcapp.FileInfo info = 1;</code>
     * @return Whether the info field is set.
     */
    boolean hasInfo();
    /**
     * <code>.samplegrpcapp.FileInfo info = 1;</code>
     * @return The info.
     */
    com.example.samplegrpcapp.ProtoFileInfo.FileInfo getInfo();
    /**
     * <code>.samplegrpcapp.FileInfo info = 1;</code>
     */
    com.example.samplegrpcapp.ProtoFileInfo.FileInfoOrBuilder getInfoOrBuilder();

    /**
     * <code>bytes chunk_data = 2;</code>
     * @return The chunkData.
     */
    com.google.protobuf.ByteString getChunkData();

    public com.example.samplegrpcapp.ProtoRequest.Request.DataCase getDataCase();
  }
  /**
   * Protobuf type {@code samplegrpcapp.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:samplegrpcapp.Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Request();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.example.samplegrpcapp.ProtoFileInfo.FileInfo.Builder subBuilder = null;
              if (dataCase_ == 1) {
                subBuilder = ((com.example.samplegrpcapp.ProtoFileInfo.FileInfo) data_).toBuilder();
              }
              data_ =
                  input.readMessage(com.example.samplegrpcapp.ProtoFileInfo.FileInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.example.samplegrpcapp.ProtoFileInfo.FileInfo) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 1;
              break;
            }
            case 18: {
              dataCase_ = 2;
              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.samplegrpcapp.ProtoRequest.internal_static_samplegrpcapp_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.samplegrpcapp.ProtoRequest.internal_static_samplegrpcapp_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.samplegrpcapp.ProtoRequest.Request.class, com.example.samplegrpcapp.ProtoRequest.Request.Builder.class);
    }

    private int dataCase_ = 0;
    private java.lang.Object data_;
    public enum DataCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      INFO(1),
      CHUNK_DATA(2),
      DATA_NOT_SET(0);
      private final int value;
      private DataCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataCase forNumber(int value) {
        switch (value) {
          case 1: return INFO;
          case 2: return CHUNK_DATA;
          case 0: return DATA_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataCase
    getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public static final int INFO_FIELD_NUMBER = 1;
    /**
     * <code>.samplegrpcapp.FileInfo info = 1;</code>
     * @return Whether the info field is set.
     */
    @java.lang.Override
    public boolean hasInfo() {
      return dataCase_ == 1;
    }
    /**
     * <code>.samplegrpcapp.FileInfo info = 1;</code>
     * @return The info.
     */
    @java.lang.Override
    public com.example.samplegrpcapp.ProtoFileInfo.FileInfo getInfo() {
      if (dataCase_ == 1) {
         return (com.example.samplegrpcapp.ProtoFileInfo.FileInfo) data_;
      }
      return com.example.samplegrpcapp.ProtoFileInfo.FileInfo.getDefaultInstance();
    }
    /**
     * <code>.samplegrpcapp.FileInfo info = 1;</code>
     */
    @java.lang.Override
    public com.example.samplegrpcapp.ProtoFileInfo.FileInfoOrBuilder getInfoOrBuilder() {
      if (dataCase_ == 1) {
         return (com.example.samplegrpcapp.ProtoFileInfo.FileInfo) data_;
      }
      return com.example.samplegrpcapp.ProtoFileInfo.FileInfo.getDefaultInstance();
    }

    public static final int CHUNK_DATA_FIELD_NUMBER = 2;
    /**
     * <code>bytes chunk_data = 2;</code>
     * @return The chunkData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getChunkData() {
      if (dataCase_ == 2) {
        return (com.google.protobuf.ByteString) data_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataCase_ == 1) {
        output.writeMessage(1, (com.example.samplegrpcapp.ProtoFileInfo.FileInfo) data_);
      }
      if (dataCase_ == 2) {
        output.writeBytes(
            2, (com.google.protobuf.ByteString) data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (com.example.samplegrpcapp.ProtoFileInfo.FileInfo) data_);
      }
      if (dataCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
              2, (com.google.protobuf.ByteString) data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.samplegrpcapp.ProtoRequest.Request)) {
        return super.equals(obj);
      }
      com.example.samplegrpcapp.ProtoRequest.Request other = (com.example.samplegrpcapp.ProtoRequest.Request) obj;

      if (!getDataCase().equals(other.getDataCase())) return false;
      switch (dataCase_) {
        case 1:
          if (!getInfo()
              .equals(other.getInfo())) return false;
          break;
        case 2:
          if (!getChunkData()
              .equals(other.getChunkData())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (dataCase_) {
        case 1:
          hash = (37 * hash) + INFO_FIELD_NUMBER;
          hash = (53 * hash) + getInfo().hashCode();
          break;
        case 2:
          hash = (37 * hash) + CHUNK_DATA_FIELD_NUMBER;
          hash = (53 * hash) + getChunkData().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.samplegrpcapp.ProtoRequest.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.samplegrpcapp.ProtoRequest.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.samplegrpcapp.ProtoRequest.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.samplegrpcapp.ProtoRequest.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.samplegrpcapp.ProtoRequest.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.samplegrpcapp.ProtoRequest.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.samplegrpcapp.ProtoRequest.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.samplegrpcapp.ProtoRequest.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.samplegrpcapp.ProtoRequest.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.samplegrpcapp.ProtoRequest.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.samplegrpcapp.ProtoRequest.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.samplegrpcapp.ProtoRequest.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.samplegrpcapp.ProtoRequest.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code samplegrpcapp.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:samplegrpcapp.Request)
        com.example.samplegrpcapp.ProtoRequest.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.samplegrpcapp.ProtoRequest.internal_static_samplegrpcapp_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.samplegrpcapp.ProtoRequest.internal_static_samplegrpcapp_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.samplegrpcapp.ProtoRequest.Request.class, com.example.samplegrpcapp.ProtoRequest.Request.Builder.class);
      }

      // Construct using com.example.samplegrpcapp.ProtoRequest.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataCase_ = 0;
        data_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.samplegrpcapp.ProtoRequest.internal_static_samplegrpcapp_Request_descriptor;
      }

      @java.lang.Override
      public com.example.samplegrpcapp.ProtoRequest.Request getDefaultInstanceForType() {
        return com.example.samplegrpcapp.ProtoRequest.Request.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.samplegrpcapp.ProtoRequest.Request build() {
        com.example.samplegrpcapp.ProtoRequest.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.samplegrpcapp.ProtoRequest.Request buildPartial() {
        com.example.samplegrpcapp.ProtoRequest.Request result = new com.example.samplegrpcapp.ProtoRequest.Request(this);
        if (dataCase_ == 1) {
          if (infoBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = infoBuilder_.build();
          }
        }
        if (dataCase_ == 2) {
          result.data_ = data_;
        }
        result.dataCase_ = dataCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.samplegrpcapp.ProtoRequest.Request) {
          return mergeFrom((com.example.samplegrpcapp.ProtoRequest.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.samplegrpcapp.ProtoRequest.Request other) {
        if (other == com.example.samplegrpcapp.ProtoRequest.Request.getDefaultInstance()) return this;
        switch (other.getDataCase()) {
          case INFO: {
            mergeInfo(other.getInfo());
            break;
          }
          case CHUNK_DATA: {
            setChunkData(other.getChunkData());
            break;
          }
          case DATA_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.samplegrpcapp.ProtoRequest.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.samplegrpcapp.ProtoRequest.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataCase_ = 0;
      private java.lang.Object data_;
      public DataCase
          getDataCase() {
        return DataCase.forNumber(
            dataCase_);
      }

      public Builder clearData() {
        dataCase_ = 0;
        data_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.samplegrpcapp.ProtoFileInfo.FileInfo, com.example.samplegrpcapp.ProtoFileInfo.FileInfo.Builder, com.example.samplegrpcapp.ProtoFileInfo.FileInfoOrBuilder> infoBuilder_;
      /**
       * <code>.samplegrpcapp.FileInfo info = 1;</code>
       * @return Whether the info field is set.
       */
      @java.lang.Override
      public boolean hasInfo() {
        return dataCase_ == 1;
      }
      /**
       * <code>.samplegrpcapp.FileInfo info = 1;</code>
       * @return The info.
       */
      @java.lang.Override
      public com.example.samplegrpcapp.ProtoFileInfo.FileInfo getInfo() {
        if (infoBuilder_ == null) {
          if (dataCase_ == 1) {
            return (com.example.samplegrpcapp.ProtoFileInfo.FileInfo) data_;
          }
          return com.example.samplegrpcapp.ProtoFileInfo.FileInfo.getDefaultInstance();
        } else {
          if (dataCase_ == 1) {
            return infoBuilder_.getMessage();
          }
          return com.example.samplegrpcapp.ProtoFileInfo.FileInfo.getDefaultInstance();
        }
      }
      /**
       * <code>.samplegrpcapp.FileInfo info = 1;</code>
       */
      public Builder setInfo(com.example.samplegrpcapp.ProtoFileInfo.FileInfo value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          infoBuilder_.setMessage(value);
        }
        dataCase_ = 1;
        return this;
      }
      /**
       * <code>.samplegrpcapp.FileInfo info = 1;</code>
       */
      public Builder setInfo(
          com.example.samplegrpcapp.ProtoFileInfo.FileInfo.Builder builderForValue) {
        if (infoBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          infoBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 1;
        return this;
      }
      /**
       * <code>.samplegrpcapp.FileInfo info = 1;</code>
       */
      public Builder mergeInfo(com.example.samplegrpcapp.ProtoFileInfo.FileInfo value) {
        if (infoBuilder_ == null) {
          if (dataCase_ == 1 &&
              data_ != com.example.samplegrpcapp.ProtoFileInfo.FileInfo.getDefaultInstance()) {
            data_ = com.example.samplegrpcapp.ProtoFileInfo.FileInfo.newBuilder((com.example.samplegrpcapp.ProtoFileInfo.FileInfo) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 1) {
            infoBuilder_.mergeFrom(value);
          }
          infoBuilder_.setMessage(value);
        }
        dataCase_ = 1;
        return this;
      }
      /**
       * <code>.samplegrpcapp.FileInfo info = 1;</code>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          if (dataCase_ == 1) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 1) {
            dataCase_ = 0;
            data_ = null;
          }
          infoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.samplegrpcapp.FileInfo info = 1;</code>
       */
      public com.example.samplegrpcapp.ProtoFileInfo.FileInfo.Builder getInfoBuilder() {
        return getInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.samplegrpcapp.FileInfo info = 1;</code>
       */
      @java.lang.Override
      public com.example.samplegrpcapp.ProtoFileInfo.FileInfoOrBuilder getInfoOrBuilder() {
        if ((dataCase_ == 1) && (infoBuilder_ != null)) {
          return infoBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 1) {
            return (com.example.samplegrpcapp.ProtoFileInfo.FileInfo) data_;
          }
          return com.example.samplegrpcapp.ProtoFileInfo.FileInfo.getDefaultInstance();
        }
      }
      /**
       * <code>.samplegrpcapp.FileInfo info = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.samplegrpcapp.ProtoFileInfo.FileInfo, com.example.samplegrpcapp.ProtoFileInfo.FileInfo.Builder, com.example.samplegrpcapp.ProtoFileInfo.FileInfoOrBuilder> 
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          if (!(dataCase_ == 1)) {
            data_ = com.example.samplegrpcapp.ProtoFileInfo.FileInfo.getDefaultInstance();
          }
          infoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.example.samplegrpcapp.ProtoFileInfo.FileInfo, com.example.samplegrpcapp.ProtoFileInfo.FileInfo.Builder, com.example.samplegrpcapp.ProtoFileInfo.FileInfoOrBuilder>(
                  (com.example.samplegrpcapp.ProtoFileInfo.FileInfo) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 1;
        onChanged();;
        return infoBuilder_;
      }

      /**
       * <code>bytes chunk_data = 2;</code>
       * @return The chunkData.
       */
      public com.google.protobuf.ByteString getChunkData() {
        if (dataCase_ == 2) {
          return (com.google.protobuf.ByteString) data_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }
      /**
       * <code>bytes chunk_data = 2;</code>
       * @param value The chunkData to set.
       * @return This builder for chaining.
       */
      public Builder setChunkData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  dataCase_ = 2;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes chunk_data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearChunkData() {
        if (dataCase_ == 2) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:samplegrpcapp.Request)
    }

    // @@protoc_insertion_point(class_scope:samplegrpcapp.Request)
    private static final com.example.samplegrpcapp.ProtoRequest.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.samplegrpcapp.ProtoRequest.Request();
    }

    public static com.example.samplegrpcapp.ProtoRequest.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      @java.lang.Override
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.samplegrpcapp.ProtoRequest.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_samplegrpcapp_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_samplegrpcapp_Request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rRequest.proto\022\rsamplegrpcapp\032\016FileInfo" +
      ".proto\"P\n\007Request\022\'\n\004info\030\001 \001(\0132\027.sample" +
      "grpcapp.FileInfoH\000\022\024\n\nchunk_data\030\002 \001(\014H\000" +
      "B\006\n\004dataB)\n\031com.example.samplegrpcappB\014P" +
      "rotoRequestb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.samplegrpcapp.ProtoFileInfo.getDescriptor(),
        });
    internal_static_samplegrpcapp_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_samplegrpcapp_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_samplegrpcapp_Request_descriptor,
        new java.lang.String[] { "Info", "ChunkData", "Data", });
    com.example.samplegrpcapp.ProtoFileInfo.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
